sonar.projectKey =
  wr - projectsbb34effab80501f441a226a9012846fd3cb153c795223c4d872ce784df422ecb;
sonar.projectName = github - template;
sonar.projectVersion = 1.0;

sonar.sourceEncoding = UTF - 8;
