name: "🐛 [BUG] -"
description: aaaaa
title: "🐛 [BUG] - "
labels: ["🐛 in-analysis", "🆘 help-needed", "🆘 new-issue"]
body:
  - type: input
    id: contact
    attributes:
      label: "Contact"
      description: Please enter your email or your Discord username & id
      placeholder: ex. user@example.com or username#id
    validations:
      required: true
