name: "🐛 [BUG] -"
description: aaaaa
title: "🐛 [BUG] - "
labels: ["🐛 in-analysis", "🆘 help-needed", "🆘 new-issue"]
body:
  - type: input
    id: contact
    attributes:
      label: "Contact"
      description: Please enter your email or your Discord username & id
      placeholder: ex. user@example.com or username#id
    validations:
      required: true
  - type: dropdown
    id: version
    attributes:
      label: "Version"
      description: What is the impacted version ?
      multiple: false
      options:
        - Latest
    validations:
      required: true
  - type: dropdown
    id: branches
    attributes:
      label: "Branch"
      description: What is the impacted branch ?
      multiple: true
      options:
        - main/
        - development/
    validations:
      required: true
