#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

SIGNATURE="Signed-off-by: `git config --global --get user.name` <`git config --global --get user.email`>"
grep -qs "^${SIGNATURE}" "$1" || echo "${SIGNATURE}" >> "$1"
