name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
categories:
  - title: '⭐ Features'
    collapse-after: 10
    label: 'type: ⭐ feature'
  - title: '🚑 Hotfix'
    collapse-after: 10
    label: 'hotfix'
  - title: '🐛 Bug Fixes'
    collapse-after: 10
    label: 'type: 🐛 bug'
  - title: '📚 Documentation'
    collapse-after: 3
    label: 'source: 📚 docs'
  - title: '⬆️ Dependency Updates'
    collapse-after: 3
    labels:
      - 'source: 🎉 ext-dependency'
      - 'source: 🎉 dependencies'
  - title: '🧰 Maintenance'
    collapse-after: 3
    label: 'type: 🚧 chore'
exclude-labels:
  - 'skip-changelog'
change-template: '- $TITLE @$AUTHOR (#$NUMBER)'
template: |
  ## What's Changed

  $CHANGES
