wr-projects/github-jstemplate:
  - OSSMETADATA
  - source: .github/
    dest: .github/
  - source: .github/workflows/
    exclude: auto-sync.yml
  - source: README.md
    replace: false
  - source: LICENSES/
    replace: false
  - source: .all-contributorsrc
    replace: false

