wr-projects/github-jstemplate:
  - OSSMETADATA
  - source: .github/workflows/
    dest: .github/workfows
    exclude: |
      auto-sync.yml
  - source: README.md
    replace: false
  - source: LICENSES/
    replace: false
  - source: .all-contributorsrc
    replace: false

