wr-projects/github-jstemplate:
  - OSSMETADATA

  - source: .github/workflows/
    dest: .github/workflows/
    exclude: |
      auto-sync.yml
      gh-pages.yml

  - source: README.md
    replace: false

  - source: LICENSES/
    replace: false

  - source: .all-contributorsrc
    replace: false

