# SPDX-FileCopyrightText: 2022 WebReady Projects <https://github.com/wr-projects/>
#
# SPDX-License-Identifier: MIT
---
name: Pipeline - Auto Sync

on:
  workflow_dispatch:
  schedule:
    - cron: '*/5 * * * *'

jobs:
  build:
    name: Auto Sync
    runs-on: ubuntu-latest
    steps:
      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_AUTOSYNCHROBOT }}
          application_private_key: ${{ secrets.PEM_AUTOSYNCHROBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          repository: wr-projects/github-template
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false

      # More info: https://github.com/rovast/sync-upstream-repo/.
      - name: GitHub Sync to Upstream Repository
        uses: BetaHuhn/repo-file-sync-action@475a6502288f55cc52e951bdd1c44d7981218478
        with:
          GH_INSTALLATION_TOKEN: ${{ steps.get_token.outputs.token }}
          CONFIG_PATH: '.github/config/workflows/sync.yml'
          GIT_EMAIL: ${{ secrets.AUTOSYNCHRO_CI_EMAIL }}
          GIT_USERNAME: ${{ secrets.AUTOSYNCHRO_CI_NAME }}
          SKIP_PR: true
