---
name: Pipeline - Autoupdate
on: push

jobs:

  # More info: https://github.com/tibdex/auto-update.
  Auto:
    name: Auto-update
    runs-on: ubuntu-latest

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443

      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_AUTOUPDATEBOT }}
          application_private_key: ${{ secrets.PEM_AUTOUPDATEBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@755da8c3cf115ac066823e79a1e1788f8940201b
        with:
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false
          fetch-depth: 0

      - name: Autoupdate
        uses: tibdex/auto-update@4081c5bdc34560b58288a010318054e63e6f4a51
        #with:
          #github_token: ${{ steps.get_token.outputs.token }}
