---
name: Pipeline - Create labels
on:
  workflow_dispatch:

jobs:
  labels:
    runs-on: ubuntu-latest
    steps:
      - uses: EndBug/label-sync@v2.0.0
        with:
          delete-other-labels: true
          config-file: https://raw.githubusercontent.com/wr-projects/github-template/main/.github/config/create-labels.yml
          token: ${{ secrets.GITHUB_TOKEN }}
