---
name: 'Pipeline - Dependabot Auto Merge'

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  automerge:
    runs-on: ubuntu-latest

    permissions:
      pull-requests: write
      contents: write

    steps:
      - name: Dependabot Auto Merge
        uses: fastify/github-action-merge-dependabot@d1b52cc4c7e618b19de8a43c7138213b277e820c
