# SPDX-FileCopyrightText: 2022 WebReady Projects <https://github.com/wr-projects/>
#
# SPDX-License-Identifier: MIT
---
name: Pipeline - Fosstars

on:
  push:
    branches: [ main ]

  schedule:
    - cron: '0 0 * * *'

permissions:
  checks: read
  contents: read
  pull-requests: write

jobs:

  create_fosstars_report:

    name: Security Rating
    runs-on: ubuntu-latest
    steps:

      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@128a63446a954579617e875aaab7d2978154e969
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.github.com:443
            github.com:443
            lgtm.com:443
            nvd.nist.gov:443
            raw.githubusercontent.com:443
            repo.maven.apache.org:443

      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_FOSSTARSBOT }}
          application_private_key: ${{ secrets.PEM_FOSSTARSBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false
          fetch-depth: 0

      # More info: https://github.com/SAP/fosstars-rating-core-action.
      - name: Security Report
        uses: SAP/fosstars-rating-core-action@213bbaa69e7364dd1a03d552d669492f7a4f6095
        with:
          rating: security
          report-branch: fosstars-report
          report-file: .github/wiki/fosstars_security_rating.md
          badge-file: .github/assets/fosstars_security_rating.svg
          #token: ${{ steps.get_token.outputs.token }}
