# SPDX-FileCopyrightText: 2022 WebReady Projects <https://github.com/wr-projects/>
#
# SPDX-License-Identifier: MIT
---
name: Pipeline - Push
on: push

permissions:
  actions: write
  contents: read
  pull-requests: read

jobs:

  gitguardian:
    name: GitGuardian Scanner
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.gitguardian.com:443
            github.com:443

      - name: Checkout & Authentication
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          persist-credentials: false
          fetch-depth: 0

      # More info: https://github.com/GitGuardian/ggshield-action
      - name: GitGuardian Scanner
        uses: GitGuardian/gg-shield-action@e1e79d4024761c6d9c55735e95cb3b0039a59a9e
        with:
          args: -v --all-policies
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.before }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  # More info: https://github.com/marketplace/actions/anchore-sbom-action
  sbom:
    needs: [gitguardian]
    name: "SBOM"
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@cba0d00b1fc9a034e1e642ea0f1103c282990604
        with:
          egress-policy: audit

      - name: Downloading Syft
        id: syft
        uses: anchore/sbom-action/download-syft@78fc58e266e87a38d4194b2137a3d4e9bcaf7ca1

      - name: Generate SBOM file
        uses: anchore/sbom-action@78fc58e266e87a38d4194b2137a3d4e9bcaf7ca1
        with:
          artifact-name: sbom.spdx
          format: spdx
          dependency-snapshot: true

      - name: Publish SBOM File
        uses: anchore/sbom-action/publish-sbom@78fc58e266e87a38d4194b2137a3d4e9bcaf7ca1
        with:
          sbom-artifact-match: ".*\\.spdx$"
