# SPDX-FileCopyrightText: 2022 WebReady Projects <https://github.com/wr-projects/>
#
# SPDX-License-Identifier: MIT
---
name: Pipeline - Push
on: push

permissions:
  actions: write
  contents: read
  pull-requests: read

jobs:

  gitguardian:
    name: GitGuardian Scanner
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
        with:
          disable-sudo: true
          egress-policy: block
          allowed-endpoints: >
            api.gitguardian.com:443
            github.com:443

      - name: Checkout & Authentication
        uses: actions/checkout@a5ac7e51b41094c92402da3b24376905380afc29
        with:
          persist-credentials: false
          fetch-depth: 0

      # More info: https://github.com/GitGuardian/ggshield-action
      - name: GitGuardian Scanner
        uses: GitGuardian/gg-shield-action@8f19f0ba4a97eb27b864c92d3ad1394fee159a41
        with:
          args: -v --all-policies
        env:
          GITHUB_PUSH_BEFORE_SHA: ${{ github.event.before }}
          GITHUB_PUSH_BASE_SHA: ${{ github.event.before }}
          GITHUB_PULL_BASE_SHA: ${{ github.event.pull_request.base.sha }}
          GITHUB_DEFAULT_BRANCH: ${{ github.event.repository.default_branch }}
          GITGUARDIAN_API_KEY: ${{ secrets.GITGUARDIAN_API_KEY }}

  # More info: https://github.com/marketplace/actions/anchore-sbom-action
  sbom:
    needs: [gitguardian]
    name: "SBOM"
    runs-on: ubuntu-latest
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@17d0e2bd7d51742c71671bd19fa12bdc9d40a3d6
        with:
          egress-policy: audit

      - name: Downloading Syft
        id: syft
        uses: anchore/sbom-action/download-syft@e8d2a6937ecead383dfe75190d104edd1f9c5751

      - name: Generate SBOM file
        uses: anchore/sbom-action@e8d2a6937ecead383dfe75190d104edd1f9c5751
        with:
          artifact-name: sbom.spdx
          format: spdx
          dependency-snapshot: true

      - name: Publish SBOM File
        uses: anchore/sbom-action/publish-sbom@e8d2a6937ecead383dfe75190d104edd1f9c5751
        with:
          sbom-artifact-match: ".*\\.spdx$"
