# SPDX-FileCopyrightText: 2022 WebReady Projects <https://github.com/wr-projects/>
#
# SPDX-License-Identifier: MIT
---
name: Pipeline - Stale
on:
  schedule:
    - cron: '0 0 * * *'

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:

  # More info:
  stale:
    runs-on: ubuntu-latest

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@a5ad31d6a139d249332a2605b85202e8c0b78450
        with:
          egress-policy: audit

      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e4e6fbf6fcc8a272781d97597969d21b3812974
        with:
          application_id: ${{ secrets.ID_STALEBOT }}
          application_private_key: ${{ secrets.PEM_STALEBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683
        with:
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false
          fetch-depth: 0

      - name: Observer INC & PRs
        uses: actions/stale@b5d41d4e1d5dceea10e7104786b73624c18a190f
        with:
          #repo-token: ${{ steps.get_token.outputs.token }}
          days-before-stale: 30
          days-before-close: 8
          stale-issue-message: "The issue has been marked as stale due to inactivity. Please show activity within 8 days or it will be automatically closed."
          stale-pr-message: "The Pull Request has been marked as stale due to inactivity. Please show activity within 8 days or it will be automatically closed."
          close-issue-message: "The issue has been automatically closed."
          close-pr-message: "The Pull Request has been automatically closed."
          stale-issue-label: 'status: ⌛ automatic-stale'
          stale-pr-label: 'status: ⌛ automatic-stale'
          close-issue-label: 'status: ✔️ automatic-closing'
          close-pr-label: 'status: ✔️ automatic-closing'
          exempt-issue-labels: 'status: 🆘 new-issue,status: ⌛ awaiting-review,status: ⌛ awaiting-reply,status: ⌛ in-progress,status: ⌛ in-review,status: ⌛ in-analysis,status: ⌛ research-needed,status: ✔️ approved-review,status: 📝 discussion,status: 💡 rfc,status: ❓ question,status: 🕜 relaunch-1,status: 🕜 relaunch-2,impact: ⚠️ critical,type: 🔐 security'
          exempt-pr-labels: 'status: 🆘 new-issue,status: ⌛ awaiting-review,status: ⌛ awaiting-reply,status: ⌛ in-progress,status: ⌛ in-review,status: ⌛ in-analysis,status: ⌛ research-needed,status: ✔️ approved-review,status: 📝 discussion,status: 💡 rfc,status: ❓ question,status: 🕜 relaunch-1,status: 🕜 relaunch-2,impact: ⚠️ critical,type: 🔐 security'
          remove-stale-when-updated: true
          delete-branch: false

      - name: Print outputs
        run: echo ${{ join(steps.stale.outputs.*, ',') }}
