# SPDX-FileCopyrightText: 2022 WebReady Projects <https://github.com/wr-projects/>
#
# SPDX-License-Identifier: MIT
---
name: Pipeline - Wiki
on:
  push:
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki.yml'
    branches:
      - main

  pull_request:
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki.yml'
    branches:
      - main

permissions:
  contents: read
  issues: read
  pull-requests: read


jobs:
  wiki:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@0080882f6c36860b6ba35c610c98ce87d4e2f26f
        with:
          egress-policy: audit

      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@d17e3a9a36850ea89f35db16c1067dd2b68ee343
        with:
          application_id: ${{ secrets.ID_WIKIBOT }}
          application_private_key: ${{ secrets.PEM_WIKIBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd
        with:
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false
          fetch-depth: 0

      # More info: https://github.com/Andrew-Chen-Wang/github-wiki-action
      - name: Push Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@64efa0a9436db17670a2259e0ac249d6f08bb352
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.WIKI_CI_EMAIL }}
          GH_NAME: ${{ secrets.WIKI_CI_NAME }}

