---
name: Pipeline - Wiki
on:
  push:
    paths:
      - '.github/wiki/**'
      - '.github/workflows/wiki.yml'
    branches:
      - main

  pull_request:
    paths:
      - 'docs/**'
      - '.github/workflows/wiki.yml'
    branches:
      - main


jobs:
  lint-docs:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]
        node: [16.10.0]

  wiki:
    runs-on: ubuntu-latest

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@ebacdc22ef6c2cfb85ee5ded8f2e640f4c776dd5
        with:
          egress-policy: audit

      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_CHECKDEPSBOT }}
          application_private_key: ${{ secrets.PEM_CHECKDEPSBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8
        with:
          persist-credentials: false
          fetch-depth: 0

