# SPDX-FileCopyrightText: 2022 WebReady Projects <https://github.com/wr-projects/>
#
# SPDX-License-Identifier: MIT
---
name: Pipeline - Wiki
on:
  push:
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki.yml'
    branches:
      - main

  pull_request:
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki.yml'
    branches:
      - main

permissions:
  contents: read
  issues: read
  pull-requests: read


jobs:
  wiki:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@1b05615854632b887b69ae1be8cbefe72d3ae423
        with:
          egress-policy: audit

      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_WIKIBOT }}
          application_private_key: ${{ secrets.PEM_WIKIBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11
        with:
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false
          fetch-depth: 0

      # More info: https://github.com/Andrew-Chen-Wang/github-wiki-action
      - name: Push Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@50650fccf3a10f741995523cf9708c53cec8912a
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.WIKI_CI_EMAIL }}
          GH_NAME: ${{ secrets.WIKI_CI_NAME }}

