# SPDX-FileCopyrightText: 2022 WebReady Projects <https://github.com/wr-projects/>
#
# SPDX-License-Identifier: MIT
---
name: Pipeline - Wiki
on:
  push:
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki.yml'
    branches:
      - main

  pull_request:
    paths:
      - 'wiki/**'
      - '.github/workflows/wiki.yml'
    branches:
      - main

permissions:
  contents: read
  issues: read
  pull-requests: read


jobs:
  wiki:
    if: ${{ !startsWith(github.head_ref, 'dependabot/') }}
    runs-on: ubuntu-latest

    steps:
      # More info: https://github.com/step-security/harden-runner.
      - name: Harden Runner
        id: harden_runner
        uses: step-security/harden-runner@55d479fb1c5bcad5a4f9099a5d9f37c8857b2845
        with:
          egress-policy: audit

      # More info: https://github.com/peter-murray/workflow-application-token-action.
      - name: Get token
        id: get_token
        uses: peter-murray/workflow-application-token-action@8e1ba3bf1619726336414f1014e37f17fbadf1db
        with:
          application_id: ${{ secrets.ID_WIKIBOT }}
          application_private_key: ${{ secrets.PEM_WIKIBOT }}

      # More info: https://github.com/actions/checkout.
      - name: Checkout & Authentication
        uses: actions/checkout@8e5e7e5ab8b370d6c329ec480221332ada57f0ab
        with:
          token: ${{ steps.get_token.outputs.token }}
          persist-credentials: false
          fetch-depth: 0

      # More info: https://github.com/Andrew-Chen-Wang/github-wiki-action
      - name: Push Wiki
        uses: Andrew-Chen-Wang/github-wiki-action@5daa8c4f90b06fb5d9989978d38b6dea8f46ad85
        env:
          WIKI_DIR: wiki/
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_MAIL: ${{ secrets.WIKI_CI_EMAIL }}
          GH_NAME: ${{ secrets.WIKI_CI_NAME }}

